// <auto-generated />
namespace LF.SysAdm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelSupllyAddress2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelSupllyAddress2));
        
        string IMigrationMetadata.Id
        {
            get { return "201707301815335_RelSupllyAddress2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
