// <auto-generated />
namespace LF.SysAdm.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class employeeService : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeService));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051317443_employeeService"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
